插件内多语言，内聚
mineadmin/MineAdmin pull request #334
Opened 2024-08-13 05:27 UTC by netyum

```
pt('mine-admin.app-store', 'check_identifier_version');

t('plugin.mine-admin.app-store.check_identifier_version');
```

插件包内，放入languages目录， 参考plugin/mine-admin/app-store

2024-08-13 13:22 UTC, People-Sea approved these changes

2024-08-13 17:40 UTC, People-Sea requested changes
修要修复CI测试

2024-08-13 17:45 UTC, People-Sea commented
fix(ci): 修复ci测试和cs fix 检查

2024-08-14 08:57 UTC, People-Sea approved these changes

2024-08-14 16:36 UTC, zds-s approved these changes

2024-08-14 16:37 UTC, merged